// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategory struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewProduct struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Categories  []int  `json:"categories"`
	Price       int    `json:"price"`
}
